src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Revscore::class)]
    private Collection $revscores;

    public function __construct()
    {
        $this->revscores = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Revscore>
     */
    public function getRevscores(): Collection
    {
        return $this->revscores;
    }

    public function addRevscore(Revscore $revscore): self
    {
        if (!$this->revscores->contains($revscore)) {
            $this->revscores->add($revscore);
            $revscore->setUser($this);
        }

        return $this;
    }

    public function removeRevscore(Revscore $revscore): self
    {
        if ($this->revscores->removeElement($revscore)) {
            // set the owning side to null (unless already changed)
            if ($revscore->getUser() === $this) {
                $revscore->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{

    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    #[Route('/access-denied', name: 'access_denied')]
    public function accessDenied(): Response
    {
        // see access_denied_url: '/access-denied'
        // in config/packages/security.yaml      

        return $this->render('security/cop.html.twig', [
            'controller_name' => 'CVController',
        ]);
    }
}

templates/security/cop.html.twig
{% extends 'base.html.twig' %}

{% block title %}Yannick Tindy CV{% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('style') }}
    {{ encore_entry_link_tags('cv') }}
        {{ encore_entry_link_tags('trunk') }}
    {# {{ encore_entry_link_tags('dayNight') }} #}
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
{% endblock %}

{% block body %}
        <div class="disp-center fluid">
        <div class="trunk">
            <img src="{{ asset('build/img/9-16/back1.png') }}">
        </div>
    </div>
{# ------ page modal -------------------------------------------------- #}
<div class="modal banner__modal fade" id="pageModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content padx1 pady2">
            <h1 class="txt-succ text-center">ACCES REFUSE !!!</h1>
            <p class="txt-light text-center">Vous n'êtes pas autorisé à accéder à cette ressource.</p>
            <hr class="hr-succ">
            <a href="{{ path('app_cv') }}" class="butn butn-succ text-center">Retour</a>
        </div>
    </div>
</div> 

    

{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('style') }}
    {{ encore_entry_link_tags('cv') }}
    {{ encore_entry_link_tags('trunk') }}
    {# {{ encore_entry_link_tags('dayNight') }} #}
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
{% endblock %}

{% block body %}
<div class="disp-center fluid">
    <div class="trunk">
        <img src="{{ asset('build/img/9-16/back1.png') }}">
    </div>
</div>

{# ------ page modal -------------------------------------------------- #}
<div class="modal banner__modal fade" id="pageModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content padx1 pady2">

            <form method="post">
                {% if error %}
                    <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                {% endif %}

                {% if app.user %}
                    <div class="txt-lum mb-3">
                        Vous êtes connecté en temps que : {{ app.user.userIdentifier }}
                    </div>
                    <a href="{{ path('app_logout') }}" class="butn butn-succ mary1">deconnexion</a>

                {% else %}   
                <h1 class="txt-succ mb-3 font-weight-normal">Identifiez vous</h1>
                {# <label for="inputUsername txt-lum">Pseudo</label> #}
                <hr class="hr-succ">
                <h6 class="txt-lum">Nom d'usage</h6>
                <input type="text" value="{{ last_username }}" name="username" id="inputUsername" class="form-control" autocomplete="username" required autofocus>
                {# <label for="inputPassword">Mot de passe</label> #}
                <hr class="hr-succ">
                <h6 class="txt-lum">Mot de passe</h6>
                <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>

                <input type="hidden" name="_csrf_token"
                    value="{{ csrf_token('authenticate') }}"
                >

                {#
                    Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
                    See https://symfony.com/doc/current/security/remember_me.html

                    <div class="checkbox mb-3">
                        <label>
                            <input type="checkbox" name="_remember_me"> Remember me
                        </label>
                    </div>
                #}

                <button class="butn butn-succ mary1" type="submit">
                    Valider
                </button>
                {# <hr class="hr-succ">
                <a href="{{ path('app_register') }}" class="butn butn-succ mary1">Créer un compte</a>     #}

                {% endif %}

 
            </form>


        </div>
    </div>
</div> 



{% endblock %}